// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/quiz-flow/FreeForm.tsx": () => import("../components/mockups/quiz-flow/FreeForm.tsx"),
  "./components/mockups/quiz-flow/MultipleChoice.tsx": () => import("../components/mockups/quiz-flow/MultipleChoice.tsx"),
  "./components/mockups/quiz-flow/WithImage.tsx": () => import("../components/mockups/quiz-flow/WithImage.tsx")
};
